name: Conventional Commits

on: pull_request

env:
  # Forcing Earthly to use colours, to make reading output easier.
  FORCE_COLOR: 1

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly.
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.15
      - name: Checkout code.
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check Conventional Commits linting.
        run: earthly --ci +check-conventional-commits-linting --from_reference "origin/${{ github.base_ref }}"
