name: GitHub Actions Workflows

on: pull_request

env:
  # Forcing Earthly to use colours, to make reading output easier.
  FORCE_COLOR: 1

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.12.
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.15
      - name: Checkout code.
        uses: actions/checkout@v4
      - name: Check GitHub Actions workflows linting.
        run: earthly +check-github-actions-workflows-linting
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Download Earthly v0.8.12.
        uses: earthly/actions-setup@v1
        with:
          version: v0.8.15
      - name: Checkout code.
        uses: actions/checkout@v4
      - name: Check formatting.
        run: earthly +check-yaml-formatting
